Some tests added but not tested

diff --git a/trunk/testsuite/bin/dotest b/trunk/testsuite/bin/dotest
--- a/trunk/testsuite/bin/dotest
+++ b/trunk/testsuite/bin/dotest
@@ -61,13 +61,14 @@ dirname=`dirname $tspec`
 
 retval=0
 
-typetest() {
-    local aflag aname aruns ainfo nline
-    aflag="$1"
-    aname="$2"
-    aruns="$3"
-    ainfo="$4"
-    nline="$5"
+latexrun() {
+    local latex aflag aname aruns ainfo nline
+    latex="$1"
+    aflag="$2"
+    aname="$3"
+    aruns="$4"
+    ainfo="$5"
+    nline="$6"
     TEXINPUTS="$KTEXINPUTS"
     case $aflag in
 	N|n) # do nothing
@@ -91,34 +92,154 @@ typetest() {
     mkdir .tmp || error 2 "$0: Cannot create directory .tmp!"
     cd .tmp || error 2 "$0: Cannot switch to directory .tmp!"
     while [ $((aruns--)) -gt 0 ]; do
-	if ! latex -interaction=batchmode ${aname} >/dev/null; then
+	if ! $latex -interaction=batchmode ${aname} >/dev/null; then
 	    $optinit && error 1 "$tspec: Init of line ${nline} (TYPE ${aname}) failed!"
 	    [ $retval -eq 1 ] || [ $retval -eq 2 ] || retval=3
-	    echo "! ${aname}: latex run failed!"
+	    echo "! ${aname}: $latex run failed!"
 	    return $retval
 	fi
     done
-    if dviselect.sh "$ainfo" ${aname%.tex}.dvi ${aname%.tex}.test.dvi; then
-	if $optinit; then
-	    cp -f ${aname%.tex}.test.dvi ../${aname%.tex}.dvi
-	    cd ..
-	    rm -rf .tmp
-	else
-	    dvitypecmp ../${aname%.tex}.dvi ${aname%.tex}.test.dvi
-	    nr=$?
-	    cd ..
-	    if [ $nr -eq 1 ] || [ $nr -eq 2 ]; then
-		retval=$nr
-		exit $retval
-	    elif [ $nr -eq 3 ]; then
-		[ $retval -eq 1 ] || [ $retval -eq 2 ] || retval=$nr
-	    else
+    return 0
+}
+
+pdftest() {
+    local aflag aname aruns ainfo nline
+    aflag="$1"
+    aname="$2"
+    aruns="$3"
+    ainfo="$4"
+    nline="$5"
+    if latexrun pdflatex "$@"; then
+	if pdfselect.sh "$ainfo" ${aname%.tex}.pdf ${aname%.tex}.test.pdf; then
+	    if $optinit; then
+		cp -f ${aname%.tex}.test.pdf ../${aname%.tex}.pdf
+		cd ..
 		rm -rf .tmp
+	    else
+		pdfcmp ../${aname%.tex}.pdf ${aname%.text}.test.pdf
+		nr=$?
+		cd ..
+		if [ $nr -eq 1 ] || [ $nr eq 2 ]; then
+		    retval=$nr
+		    exit $retval
+		elif [ $nr -eq 3 ]; then
+		    [ $retval -eq 1 ] || [ $retval -eq 2 ] || retval=$nr
+		else
+		    rm -rf .tmp
+		fi
 	    fi
+	else
+	    retval=2
+	    exit $retval
 	fi
-    else
-	retval=2
-	exit $retval
+    fi
+    return $retval
+}
+
+dvitest() {
+    local aflag aname aruns ainfo nline
+    aflag="$1"
+    aname="$2"
+    aruns="$3"
+    ainfo="$4"
+    nline="$5"
+    if latexrun latex "$@"; then
+	if dviselect.sh "$ainfo" ${aname%.tex}.dvi ${aname%.tex}.test.dvi; then
+	    if $optinit; then
+		cp -f ${aname%.tex}.test.dvi ../${aname%.tex}.dvi
+		cd ..
+		rm -rf .tmp
+	    else
+		dvicmp ../${aname%.tex}.dvi ${aname%.tex}.test.dvi
+		nr=$?
+		cd ..
+		if [ $nr -eq 1 ] || [ $nr -eq 2 ]; then
+		    retval=$nr
+		    exit $retval
+		elif [ $nr -eq 3 ]; then
+		    [ $retval -eq 1 ] || [ $retval -eq 2 ] || retval=$nr
+		else
+		    rm -rf .tmp
+		fi
+	    fi
+	else
+	    retval=2
+	    exit $retval
+	fi
+    fi
+    return $retval
+}
+
+pstest() {
+    local aflag aname aruns ainfo nline
+    aflag="$1"
+    aname="$2"
+    aruns="$3"
+    ainfo="$4"
+    nline="$5"
+    if latexrun latex "$@"; then
+	if dviselect.sh "$ainfo" ${aname%.tex}.dvi ${aname%.tex}.test.dvi; then
+	    if dvips ${aname%.tex}.test.dvi -o ${aname%.tex}.test.ps; then
+		if $optinit; then
+		    cp -f ${aname%.tex}.test.ps ../${aname%.tex}.ps
+		    cd ..
+		    rm -rf .tmp
+		else
+		    pdfcmp ../${aname%.tex}.ps ${aname%.tex}.test.ps
+		    nr=$?
+		    cd ..
+		    if [ $nr -eq 1 ] || [ $nr -eq 2 ]; then
+			retval=$nr
+			exit $retval
+		    elif [ $nr -eq 3 ]; then
+			[ $retval -eq 1 ] || [ $retval -eq 2 ] || retval=$nr
+		    else
+			rm -rf .tmp
+		    fi
+		fi
+	    else
+		echo "${aname}: Error calling dvips!\n" >&2
+		retval=2
+		exit $retval
+	    fi
+	else
+	    retval=2
+	    exit $retval
+	fi
+    fi
+    return $retval
+}
+
+typetest() {
+    local aflag aname aruns ainfo nline
+    aflag="$1"
+    aname="$2"
+    aruns="$3"
+    ainfo="$4"
+    nline="$5"
+    if latexrun latex "$@"; then
+	if dviselect.sh "$ainfo" ${aname%.tex}.dvi ${aname%.tex}.test.dvi; then
+	    if $optinit; then
+		cp -f ${aname%.tex}.test.dvi ../${aname%.tex}.dvi
+		cd ..
+		rm -rf .tmp
+	    else
+		dvitypecmp ../${aname%.tex}.dvi ${aname%.tex}.test.dvi
+		nr=$?
+		cd ..
+		if [ $nr -eq 1 ] || [ $nr -eq 2 ]; then
+		    retval=$nr
+		    exit $retval
+		elif [ $nr -eq 3 ]; then
+		    [ $retval -eq 1 ] || [ $retval -eq 2 ] || retval=$nr
+		else
+		    rm -rf .tmp
+		fi
+	    fi
+	else
+	    retval=2
+	    exit $retval
+	fi
     fi
     return $retval
 }
@@ -131,6 +252,15 @@ readtspec() {
 	    '') # empty line
 		;;
 	    \#*) # comment
+		;;
+	    DVI)  # DVI test
+		dvitest "$aflag" "$aname" "$aruns" "$ainfo"
+		;;
+	    PDF)  # PDF test
+		pdftest "$aflag" "$aname" "$aruns" "$ainfo"
+		;;
+	    PS)   # PS test
+		pstest "$aflag" "$aname" "$aruns" "$ainfo"
 		;;
 	    TYPE) # type test
 		typetest "$aflag" "$aname" "$aruns" "$ainfo"
